[toolchain]

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
zuski = "7yypKnJAZ9JjaemSA3A2Ha378sebeh6ciSvMy6pzHzdq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.testnet.sonic.game"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
